#!/usr/bin/env bash
set -e

if [[ -d build ]]; then
    rm -rf build
fi

if [[ -d devel ]]; then
    rm -rf devel
fi

catkin_make clean
source devel/setup.bash

catkin_make -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage" -DCMAKE_C_FLAGS="-fprofile-arcs -ftest-coverage" -DCMAKE_SHARED_LINKER_FLAGS="-lgcov --coverage"  $@
